apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongoems
  name: mongoems
  namespace: cybpune-alm-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongoems
    spec:
      containers:
      - image: abhishekbadwaik/mongodb
        name: mongoems
        ports:
        - name: mongoems
          containerPort: 27017
