kind: Service
apiVersion: v1
metadata:
  labels:
    app: node-emsapp-service
  name: node-emsapp-service
  namespace: cybpune-alm-dev
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 5000
  selector:
    app: node-emsapp
