apiVersion: v1
kind: Service
metadata:
  name: mongoems-svc
  labels:
    name: mongoems-svc
  namespace: cybpune-alm-dev
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    name: mongoems-svc
