kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx-app-service
  name: nginx-app-service
  namespace: cybpune-alm-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-app
