apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-emsapp
  labels:
    name: node-emsapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: node-emsapp
    spec:
      containers:
      - image: gauravsj/nodejs-hello
        name: node-emsapp
        ports:
        - containerPort: 8081
