apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: cybpune-alm-dev
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        env:
          - name: WORDPRESS_DB_PASSWORD
            # change this - must match mysql.yaml password
            value: admin
          - name: WORDPRESS_DB_HOST
            value: 10.109.94.197
