apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: cybpune-alm-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongoems 
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
          # change this
            value: admin
        ports:
          - containerPort: 3306
            name: mysql
