apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volumedb
spec:
  capacity:
    storage: 2Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs: 
    endpoints: glusterfs-cluster 
    path: testvoldb
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 
